Refactor/break kzg srs
ConsenSys/gnark-crypto pull request #378
Opened 2023-04-07 21:55 UTC by Tabaie

The KZG SRS breaks up naturally into a prover component (G1[:]) and a verifier component (G1[0], G2[0:2]), which only have one G1 point in common (which is usually standardized and can be omitted anyway).
Treating it as a single object results in very long Plonk verifying keys for example, which can be problematic in Smart Contracts.

This PR implements the break-up.

WARNING: I've removed pretty much all pass-by-pointers I encountered. In case some of that was performance-critical, lmk and I'll add it back in.

2023-04-11 15:03 UTC, gbotrel requested changes

2023-04-11 15:03 UTC, gbotrel commented on internal/generator/kzg/template/marshal.go.tmpl
> +// WriteRawTo writes binary encoding of Proof to w without point compression
Proof -> VerifyingKey

2023-04-11 15:03 UTC, gbotrel commented on internal/generator/kzg/template/marshal.go.tmpl
> +	// encode the VerifyingKey
bad comment.

Here I would rather call srs.Pk.WriteTo, srs.Vk.WriteTo, easier to maintain for future changes.

There is a duplicate point but it's not a crazy overhead.

2023-04-11 15:03 UTC, gbotrel commented on internal/generator/kzg/template/marshal.go.tmpl
> +		&pk.G1,
just `dec.Decode(&pk.G1)`

2023-04-11 15:03 UTC, gbotrel commented on internal/generator/kzg/template/marshal.go.tmpl
> +		&srs.Vk.G2[0],
same `srs.Pk.ReadFrom...` `srs.Vk.ReadFrom(...)`

2023-04-13 21:19 UTC, ThomasPiellard commented
Could you modify 
```
        _, err := foldedQuotients.MultiExp(quotients, randomNumbers, config)
	if err != nil {
		return nil
	}
```

to 
```
        _, err := foldedQuotients.MultiExp(quotients, randomNumbers, config)
 	if err != nil {
		return err
	}
```

in BatchVerifyMultiPoints in the kzg.go files (e.g. l.419 for bls377) ? (Spotted by @kevaundray )

2023-04-17 13:53 UTC, gbotrel approved these changes
minor comment on godoc format but lgtm 👍

2023-04-17 13:53 UTC, gbotrel commented on internal/generator/kzg/template/kzg.go.tmpl
> +type ProvingKey struct {
godoc format: struct doc should be // ProvingKey ...

(else it isn't render properly in godoc)

2023-04-18 14:18 UTC, ThomasPiellard approved these changes

2023-04-20 02:55 UTC, merged