Fix/incorrect polynomial evaluation
Consensys/gnark-crypto pull request #539
Opened 2024-09-16 17:14 UTC by ThomasPiellard

# Description

Variable was not assigned when evaluating a shifted polynomial with shift > 5.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I did not modify files generated from templates
- [x] `golangci-lint` does not output errors locally
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-09-16 17:48 UTC, gbotrel requested changes

2024-09-16 17:48 UTC, gbotrel commented on internal/generator/iop/template/polynomial.go.tmpl
>  		if err != nil {
this err check should be moved outside the `if` scope

2024-09-17 08:42 UTC, ivokub approved these changes
LGTM

2024-09-25 13:17 UTC, gbotrel approved these changes

2024-09-25 13:17 UTC, merged