feat: add `BabyBear` and `KoalaBear` 31bits fields vanilla Go impl
Consensys/gnark-crypto pull request #558
Opened 2024-11-25 20:26 UTC by gbotrel

# Description

Adds `31bit` fields support (i.e. template generate Golang code with `uint32`).

Perf work and vectorization (AVX, NEON) to come in future PRs.

```
		{"koalabear", "0x7f000001"}, // 2^31 - 2^24 + 1 ==> the cube map (x -> x^3) is an automorphism of the multiplicative group
		{"babybear", "0x78000001"},  // 2^31 - 2^27 + 1 ==> 2-adicity 27
```

2024-12-02 04:01 UTC, Tabaie requested changes

2024-12-02 04:01 UTC, Tabaie commented on field/babybear/element.go
> +type Element [1]uint32
> Since ≤32bit moduli have their own template I think it's better for element to simply alias uint32.

I see that the premise is not true. It may still look cleaner to just alias uint32.

2024-12-03 21:52 UTC, gbotrel commented on field/babybear/element.go
> +	q  uint32 = q0
yes, template generation business ; does'nt matter though, it s a constant / will be propagated by compiler

2024-12-03 21:53 UTC, gbotrel commented on field/babybear/element.go
> +type Element [1]uint32
it would make the template more verbose; most places have templates that operates on array of words.
Normally an user should never care about underlying repr; it's more elegant to have uint32 directly but doesn't change anything perf-wise

2024-12-03 21:53 UTC, gbotrel commented on field/babybear/element.go
> +	z[0], _ = bits.Add32(x[0], y[0], 0)
there is none :) will add to needed modif

2024-12-03 21:55 UTC, gbotrel commented on field/babybear/element.go
> +	for {
yes I believe that was the recommended solution from a previous audit

2024-12-04 20:26 UTC, gbotrel commented on field/babybear/element.go
> +// _mulGeneric is unoptimized textbook CIOS
will fix in a separate PR to avoid having unrelated diff

2024-12-04 20:27 UTC, gbotrel commented on field/babybear/element.go
> +	t[1], D = bits.Add32(t[1], C, 0)
good catch, but for nbwords == 1 in our configuration, this method is used for test purposes (i.e. vanilla unroll of the CIOS text book against the "real" mul we use)

2024-12-10 19:00 UTC, merged